// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutManager.Data;

#nullable disable

namespace WorkoutManager.Infrastructure.Migrations
{
    [DbContext(typeof(WorkoutDbContext))]
    partial class WorkoutDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ContraindicationEquipment", b =>
                {
                    b.Property<int>("ContraindicationsId")
                        .HasColumnType("int");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("int");

                    b.HasKey("ContraindicationsId", "EquipmentId");

                    b.HasIndex("EquipmentId");

                    b.ToTable("EquipmentContraindications", (string)null);
                });

            modelBuilder.Entity("ContraindicationExercise", b =>
                {
                    b.Property<int>("ContraindicationsId")
                        .HasColumnType("int");

                    b.Property<int>("ExercisesId")
                        .HasColumnType("int");

                    b.HasKey("ContraindicationsId", "ExercisesId");

                    b.HasIndex("ExercisesId");

                    b.ToTable("ExerciseContraindications", (string)null);
                });

            modelBuilder.Entity("ExerciseExerciseGroup", b =>
                {
                    b.Property<int>("ExerciseGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("ExercisesId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseGroupsId", "ExercisesId");

                    b.HasIndex("ExercisesId");

                    b.ToTable("ExerciseExerciseGroups", (string)null);
                });

            modelBuilder.Entity("ExerciseGroupWorkoutProgram", b =>
                {
                    b.Property<int>("ExerciseGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("WorkoutProgramId")
                        .HasColumnType("int");

                    b.HasKey("ExerciseGroupsId", "WorkoutProgramId");

                    b.HasIndex("WorkoutProgramId");

                    b.ToTable("WorkoutProgramExerciseGroups", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityRole");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("nvarchar(34)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasDiscriminator().HasValue("IdentityUserRole<string>");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("UserWorkoutProgram", b =>
                {
                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("WorkoutProgramsId")
                        .HasColumnType("int");

                    b.HasKey("UsersId", "WorkoutProgramsId");

                    b.HasIndex("WorkoutProgramsId");

                    b.ToTable("WorkoutProgramUsers", (string)null);
                });

            modelBuilder.Entity("WorkoutManager.Models.Contraindication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Contraindications");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Avoid high-intensity exercises.",
                            IsDeleted = false,
                            Name = "High Blood Pressure"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Avoid exercises that put strain on the knees.",
                            IsDeleted = false,
                            Name = "Knee Injury"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Avoid heavy lifting and twisting movements.",
                            IsDeleted = false,
                            Name = "Back Pain"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Avoid strenuous cardiovascular activities.",
                            IsDeleted = false,
                            Name = "Heart Condition"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Avoid exercises that involve lying flat on the back after the first trimester.",
                            IsDeleted = false,
                            Name = "Pregnancy"
                        });
                });

            modelBuilder.Entity("WorkoutManager.Models.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EquipmentCategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentCategoryId");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A machine for walking or running while staying in one place.",
                            EquipmentCategoryId = 1,
                            IsDeleted = false,
                            Name = "Treadmill"
                        },
                        new
                        {
                            Id = 2,
                            Description = "A type of free weight used in weight training.",
                            EquipmentCategoryId = 2,
                            IsDeleted = false,
                            Name = "Dumbbells"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A mat used for yoga practice.",
                            EquipmentCategoryId = 2,
                            IsDeleted = false,
                            Name = "Yoga Mat"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A stationary bike used for cardiovascular workouts.",
                            EquipmentCategoryId = 3,
                            IsDeleted = false,
                            Name = "Exercise Bike"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Elastic bands used for strength training.",
                            EquipmentCategoryId = 2,
                            IsDeleted = false,
                            Name = "Resistance Bands"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Not required.",
                            EquipmentCategoryId = 4,
                            IsDeleted = false,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("WorkoutManager.Models.EquipmentCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Equipment used for cardiovascular workouts.",
                            IsDeleted = false,
                            Name = "Cardio"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Equipment used for strength and resistance training.",
                            IsDeleted = false,
                            Name = "Strength"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Equipment used for improving flexibility and balance.",
                            IsDeleted = false,
                            Name = "Flexibility"
                        },
                        new
                        {
                            Id = 4,
                            Description = "No equipment required.",
                            IsDeleted = false,
                            Name = "None"
                        });
                });

            modelBuilder.Entity("WorkoutManager.Models.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EquipmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("EquipmentId");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EquipmentId = 6,
                            IsDeleted = false,
                            Name = "Jumping Jacks",
                            Quantity = 30m,
                            Unit = "reps"
                        },
                        new
                        {
                            Id = 2,
                            EquipmentId = 6,
                            IsDeleted = false,
                            Name = "Push-ups",
                            Quantity = 15m,
                            Unit = "reps"
                        },
                        new
                        {
                            Id = 3,
                            EquipmentId = 2,
                            IsDeleted = false,
                            Name = "Squats",
                            Quantity = 20m,
                            Unit = "reps"
                        },
                        new
                        {
                            Id = 4,
                            EquipmentId = 6,
                            IsDeleted = false,
                            Name = "Plank",
                            Quantity = 60m,
                            Unit = "seconds"
                        },
                        new
                        {
                            Id = 5,
                            EquipmentId = 2,
                            IsDeleted = false,
                            Name = "Lunges",
                            Quantity = 20m,
                            Unit = "reps"
                        },
                        new
                        {
                            Id = 6,
                            EquipmentId = 4,
                            IsDeleted = false,
                            Name = "Burpees",
                            Quantity = 10m,
                            Unit = "reps"
                        },
                        new
                        {
                            Id = 7,
                            EquipmentId = 1,
                            IsDeleted = false,
                            Name = "Mountain Climbers",
                            Quantity = 30m,
                            Unit = "seconds"
                        },
                        new
                        {
                            Id = 8,
                            EquipmentId = 1,
                            IsDeleted = false,
                            Name = "High Knees",
                            Quantity = 30m,
                            Unit = "seconds"
                        });
                });

            modelBuilder.Entity("WorkoutManager.Models.ExerciseGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseGroups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            Name = "Warm-up Exercises"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            Name = "Main Exercises"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            Name = "Strength Training"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            Name = "Cool-down Exercises"
                        });
                });

            modelBuilder.Entity("WorkoutManager.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("WorkoutManager.Models.WorkoutProgram", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("MainWorkoutDurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("WarmupDurationMinutes")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("WorkoutPrograms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodeName = "BEGINNER_FULL_BODY",
                            Description = "A full body workout program for beginners.",
                            IsDeleted = false,
                            MainWorkoutDurationMinutes = 30,
                            Title = "Beginner Full Body Workout",
                            WarmupDurationMinutes = 10
                        },
                        new
                        {
                            Id = 2,
                            CodeName = "INTERMEDIATE_CARDIO",
                            Description = "An intermediate level cardio workout program.",
                            IsDeleted = false,
                            MainWorkoutDurationMinutes = 45,
                            Title = "Intermediate Cardio Blast"
                        },
                        new
                        {
                            Id = 3,
                            CodeName = "ADVANCED_STRENGTH",
                            Description = "An advanced strength training workout program.",
                            IsDeleted = false,
                            MainWorkoutDurationMinutes = 60,
                            Title = "Advanced Strength Training"
                        });
                });

            modelBuilder.Entity("WorkoutManager.Domain.Entities.Role", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("Role");

                    b.HasData(
                        new
                        {
                            Id = "2847bd82-071c-44b2-8f6b-5540c7d70370",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2bae9d45-61c1-44ba-9e26-9ad7b0752b53",
                            Name = "Writer",
                            NormalizedName = "WRITER"
                        },
                        new
                        {
                            Id = "1ccd9ab3-6fb3-445e-ac76-2dc8b806232e",
                            Name = "Reader",
                            NormalizedName = "READER"
                        });
                });

            modelBuilder.Entity("WorkoutManager.Domain.Entities.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUserRole<string>");

                    b.HasDiscriminator().HasValue("UserRole");
                });

            modelBuilder.Entity("ContraindicationEquipment", b =>
                {
                    b.HasOne("WorkoutManager.Models.Contraindication", null)
                        .WithMany()
                        .HasForeignKey("ContraindicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutManager.Models.Equipment", null)
                        .WithMany()
                        .HasForeignKey("EquipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ContraindicationExercise", b =>
                {
                    b.HasOne("WorkoutManager.Models.Contraindication", null)
                        .WithMany()
                        .HasForeignKey("ContraindicationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutManager.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseExerciseGroup", b =>
                {
                    b.HasOne("WorkoutManager.Models.ExerciseGroup", null)
                        .WithMany()
                        .HasForeignKey("ExerciseGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutManager.Models.Exercise", null)
                        .WithMany()
                        .HasForeignKey("ExercisesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExerciseGroupWorkoutProgram", b =>
                {
                    b.HasOne("WorkoutManager.Models.ExerciseGroup", null)
                        .WithMany()
                        .HasForeignKey("ExerciseGroupsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutManager.Models.WorkoutProgram", null)
                        .WithMany()
                        .HasForeignKey("WorkoutProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("WorkoutManager.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("WorkoutManager.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("WorkoutManager.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("UserWorkoutProgram", b =>
                {
                    b.HasOne("WorkoutManager.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkoutManager.Models.WorkoutProgram", null)
                        .WithMany()
                        .HasForeignKey("WorkoutProgramsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutManager.Models.Equipment", b =>
                {
                    b.HasOne("WorkoutManager.Models.EquipmentCategory", "EquipmentCategory")
                        .WithMany("Equipment")
                        .HasForeignKey("EquipmentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EquipmentCategory");
                });

            modelBuilder.Entity("WorkoutManager.Models.Exercise", b =>
                {
                    b.HasOne("WorkoutManager.Models.Equipment", "Equipment")
                        .WithMany("Exercises")
                        .HasForeignKey("EquipmentId");

                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("WorkoutManager.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("WorkoutManager.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_AspNetUserRoles_AspNetRoles_RoleId1");

                    b.HasOne("WorkoutManager.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("WorkoutManager.Models.Equipment", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("WorkoutManager.Models.EquipmentCategory", b =>
                {
                    b.Navigation("Equipment");
                });

            modelBuilder.Entity("WorkoutManager.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("WorkoutManager.Domain.Entities.Role", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
